language: node_js
node_js:
  - "10"
before_script:
  - npx version-from-git --travis --no-git-tag-version
  - npm run bootstrap
  - npm run build
before_deploy:
  - cp -r packages/component/lib .
deploy:
  - provider: npm
    api_key:
      secure: "Rb//K/GKHFtXZViSQtwhlzxrCyPEAy2mgRnqz346VCtjqPKiwrpD3hhkbQNowOfSQjZ4TtY+5Pl7NS8tq0Kq51Exd9Yx+/xJoUXItcJaElT1z1AoeR8UXJLsjU6syP8RIHvb3yBNdLtZfoNpiIzEZcyDFB4H6XrycPWRviDER+oI1qdoVfL1uQGh2kbtcTpWYjc9+vI3qzlC0sWiopHRiaM+yIaM3IMEQM+5xZbTgfM90AN+qFATJ7b93vbqMX7tVDAuG+ceXRrncedonpHvmZaDWZUQgA67sCPMB4/d5C4cg6XFrGMoHKC82vJ1wvGY5g0Hb79thUQDSXrx69hit0lbFr5wb5G93xHyu6KfPgyz+zRRy3sbnVDzP7WJBFn8l/EKUV6WdoIHOq9VaemDiM8tAVnOtATGwylgu61120Xd6z9VgAq67ipiRbcll1nZ2jExX45NynM6SofBAffHOtJkK4gQh4f01N8KNwVePW30Q4mZkze4YYaptjvHcmoDnAK3vU6LX9nwpyKiseanx6ZfSn+ckRIGwXLPwtDWAFVcgeJjbvlVNe6cjboX0YGK8pBm4NBG6K+YpwLDT+m9Sn2ZepW+U2lm5R+2BwEIzFk4ZL5x+VbFrJ+7frbrcYqDOnZLeDC+kpLSX+uEVJTD1KlSeueoWt3zlfQzTB/X2K4="
    email: "compulim@hotmail.com"
    on:
      branch: master
    skip_cleanup: true
    tag: master
  - provider: npm
    api_key:
      secure: "Rb//K/GKHFtXZViSQtwhlzxrCyPEAy2mgRnqz346VCtjqPKiwrpD3hhkbQNowOfSQjZ4TtY+5Pl7NS8tq0Kq51Exd9Yx+/xJoUXItcJaElT1z1AoeR8UXJLsjU6syP8RIHvb3yBNdLtZfoNpiIzEZcyDFB4H6XrycPWRviDER+oI1qdoVfL1uQGh2kbtcTpWYjc9+vI3qzlC0sWiopHRiaM+yIaM3IMEQM+5xZbTgfM90AN+qFATJ7b93vbqMX7tVDAuG+ceXRrncedonpHvmZaDWZUQgA67sCPMB4/d5C4cg6XFrGMoHKC82vJ1wvGY5g0Hb79thUQDSXrx69hit0lbFr5wb5G93xHyu6KfPgyz+zRRy3sbnVDzP7WJBFn8l/EKUV6WdoIHOq9VaemDiM8tAVnOtATGwylgu61120Xd6z9VgAq67ipiRbcll1nZ2jExX45NynM6SofBAffHOtJkK4gQh4f01N8KNwVePW30Q4mZkze4YYaptjvHcmoDnAK3vU6LX9nwpyKiseanx6ZfSn+ckRIGwXLPwtDWAFVcgeJjbvlVNe6cjboX0YGK8pBm4NBG6K+YpwLDT+m9Sn2ZepW+U2lm5R+2BwEIzFk4ZL5x+VbFrJ+7frbrcYqDOnZLeDC+kpLSX+uEVJTD1KlSeueoWt3zlfQzTB/X2K4="
    email: "compulim@hotmail.com"
    on:
      tags: true
    skip_cleanup: true
  - provider: pages
    skip-cleanup: true
    github-token:
      secure: "By9mOa/fbj3aLs7CF+zKD+9n4j6D4hR2oFRoLL6dCDmCbBXOo+ddxB0U8mR9dg2abxo5cXRXU5yxfYp304Lb47YHfC/ayJAAYzvbgkn92Gq0V3jBmZ2pZ8ldbjUJpPQfnavSPmy4zDB53YMYXxoG8vfaRUk6mltapKHvN+Mw0dwuc9Ez+w4XTpnOk1NEmFGpw6vTFcBKkQoj6yhzRljQKPY3cFZqUnx/FEWBC0pAsufrGR946itsZAuRSVjkRj6BnzFqs5zZeaHs07sdb75+RSqcS2yadilhJqIumD64f12qMYfQH6uICeyHMxnNZkvGwcXcc5034FTchUyAxQxc0mg2t6CZWztbSAQ9aCvQ4p2jZZLIkaATee32/MEkx9vaJP0IB/GBJ5sIoBlQdpAIRZljq6nyBkR+H18k3Pk2spePsaGaiqrggaPzGbGPHnj74ENMXoDym/lsehhNOSn8Wwzb1EfF+8AAOg3FOUq4m8G42/ed5J8WVKgP4B+Pd89tRWl2dD+DXly1dDD64vHvOyf0yzdL8FtWsGdKd6XKiOnA0GSWEjsMtj9LOaYmHEW1vANv9uBjqMcwBdRSA2xiR2+ADcP1kMYHJZcLWKjVSkPhMDlIyTQe4WAEMCyxqmufEtLbTVwhDwFtJbucSB2bS+TzrRYEjahqkTlVCnmPyYg="
    on:
      branch: master
    local-dir: packages/playground/build
  - provider: releases
    api_key:
      secure: "By9mOa/fbj3aLs7CF+zKD+9n4j6D4hR2oFRoLL6dCDmCbBXOo+ddxB0U8mR9dg2abxo5cXRXU5yxfYp304Lb47YHfC/ayJAAYzvbgkn92Gq0V3jBmZ2pZ8ldbjUJpPQfnavSPmy4zDB53YMYXxoG8vfaRUk6mltapKHvN+Mw0dwuc9Ez+w4XTpnOk1NEmFGpw6vTFcBKkQoj6yhzRljQKPY3cFZqUnx/FEWBC0pAsufrGR946itsZAuRSVjkRj6BnzFqs5zZeaHs07sdb75+RSqcS2yadilhJqIumD64f12qMYfQH6uICeyHMxnNZkvGwcXcc5034FTchUyAxQxc0mg2t6CZWztbSAQ9aCvQ4p2jZZLIkaATee32/MEkx9vaJP0IB/GBJ5sIoBlQdpAIRZljq6nyBkR+H18k3Pk2spePsaGaiqrggaPzGbGPHnj74ENMXoDym/lsehhNOSn8Wwzb1EfF+8AAOg3FOUq4m8G42/ed5J8WVKgP4B+Pd89tRWl2dD+DXly1dDD64vHvOyf0yzdL8FtWsGdKd6XKiOnA0GSWEjsMtj9LOaYmHEW1vANv9uBjqMcwBdRSA2xiR2+ADcP1kMYHJZcLWKjVSkPhMDlIyTQe4WAEMCyxqmufEtLbTVwhDwFtJbucSB2bS+TzrRYEjahqkTlVCnmPyYg="
    on:
      tags: true
    skip_cleanup: true
