language: node_js
node_js:
  - "10"
before_script:
  - npx version-from-git --travis --no-git-tag-version
  - npm run bootstrap
  - node scripts/syncVersion
  - npm run build
before_deploy:
  - cp -r packages/component/lib .
deploy:
  - provider: npm
    api_key:
      secure: "SLauNAZI0tTACb5o5pr/MDBzcwXmDWXW0cL77XARwW28kfLiboYqvC4HY1/9s/Z33FQOLmqp/e7BI3JozUW2f3GJ//z6UVpVfaDxTfI9BDLSoC6OH+I7JP04+oezpjZJ+xcYcQy3iPCjYt05+i/OvGHyO4VW3JV5K0AYE4asskfuh5ED9t6PTUh9JCyI/H/WXb51E3b6dbjpWSXMJ8Vsn6sH3Gm+3uX5s5t6E485usfuZnZ24Xbkj1GveJXISI4ltB6JhHiKmnUVZm1rFsMrp9xPx4opsAZpPEAbhPqRC30kmzoNqhgyT8AhkLJyoUIOnKfgXTWpC1WmMWqJasWakU/O/kKW/KEs4YIldUuhiHH1lM9QUGaM0e/Y5Iv7JL9v6vNlnnS856oXo8I7sH0Z3syJL7r3mtRN0l/6bKjRq944TnSvcd2nZ+7ILivMc6OK0ddCk0kH+uoYkYOCoyEfE8KrHBI4xfhgLOTxFAgztKznqxX0aTrL8/HFKCzuinF37rB6IBntLRxsxHrvW5dqQtbbFpdMSNH0/tVqdLuURD+rheOO4ZwUioaYgAB0uGKqFJv4ZqEJTmdicyuzm/dolvrOMkceaQVZlQ6N9rjWRlGrMvq4JLXnJg6etr8qF6Z9H4dGfRnE4KYs/eMyhqwHKLdXQYfogcEfAA5KSEucKTc="
    email: "compulim@hotmail.com"
    on:
      branch: master
    skip_cleanup: true
    tag: master
  - provider: npm
    api_key:
      secure: "SLauNAZI0tTACb5o5pr/MDBzcwXmDWXW0cL77XARwW28kfLiboYqvC4HY1/9s/Z33FQOLmqp/e7BI3JozUW2f3GJ//z6UVpVfaDxTfI9BDLSoC6OH+I7JP04+oezpjZJ+xcYcQy3iPCjYt05+i/OvGHyO4VW3JV5K0AYE4asskfuh5ED9t6PTUh9JCyI/H/WXb51E3b6dbjpWSXMJ8Vsn6sH3Gm+3uX5s5t6E485usfuZnZ24Xbkj1GveJXISI4ltB6JhHiKmnUVZm1rFsMrp9xPx4opsAZpPEAbhPqRC30kmzoNqhgyT8AhkLJyoUIOnKfgXTWpC1WmMWqJasWakU/O/kKW/KEs4YIldUuhiHH1lM9QUGaM0e/Y5Iv7JL9v6vNlnnS856oXo8I7sH0Z3syJL7r3mtRN0l/6bKjRq944TnSvcd2nZ+7ILivMc6OK0ddCk0kH+uoYkYOCoyEfE8KrHBI4xfhgLOTxFAgztKznqxX0aTrL8/HFKCzuinF37rB6IBntLRxsxHrvW5dqQtbbFpdMSNH0/tVqdLuURD+rheOO4ZwUioaYgAB0uGKqFJv4ZqEJTmdicyuzm/dolvrOMkceaQVZlQ6N9rjWRlGrMvq4JLXnJg6etr8qF6Z9H4dGfRnE4KYs/eMyhqwHKLdXQYfogcEfAA5KSEucKTc="
    email: "compulim@hotmail.com"
    on:
      tags: true
    skip_cleanup: true
  - provider: pages
    skip-cleanup: true
    github-token:
      secure: "By9mOa/fbj3aLs7CF+zKD+9n4j6D4hR2oFRoLL6dCDmCbBXOo+ddxB0U8mR9dg2abxo5cXRXU5yxfYp304Lb47YHfC/ayJAAYzvbgkn92Gq0V3jBmZ2pZ8ldbjUJpPQfnavSPmy4zDB53YMYXxoG8vfaRUk6mltapKHvN+Mw0dwuc9Ez+w4XTpnOk1NEmFGpw6vTFcBKkQoj6yhzRljQKPY3cFZqUnx/FEWBC0pAsufrGR946itsZAuRSVjkRj6BnzFqs5zZeaHs07sdb75+RSqcS2yadilhJqIumD64f12qMYfQH6uICeyHMxnNZkvGwcXcc5034FTchUyAxQxc0mg2t6CZWztbSAQ9aCvQ4p2jZZLIkaATee32/MEkx9vaJP0IB/GBJ5sIoBlQdpAIRZljq6nyBkR+H18k3Pk2spePsaGaiqrggaPzGbGPHnj74ENMXoDym/lsehhNOSn8Wwzb1EfF+8AAOg3FOUq4m8G42/ed5J8WVKgP4B+Pd89tRWl2dD+DXly1dDD64vHvOyf0yzdL8FtWsGdKd6XKiOnA0GSWEjsMtj9LOaYmHEW1vANv9uBjqMcwBdRSA2xiR2+ADcP1kMYHJZcLWKjVSkPhMDlIyTQe4WAEMCyxqmufEtLbTVwhDwFtJbucSB2bS+TzrRYEjahqkTlVCnmPyYg="
    on:
      branch: master
    local-dir: packages/playground/build
  - provider: releases
    api_key:
      secure: "By9mOa/fbj3aLs7CF+zKD+9n4j6D4hR2oFRoLL6dCDmCbBXOo+ddxB0U8mR9dg2abxo5cXRXU5yxfYp304Lb47YHfC/ayJAAYzvbgkn92Gq0V3jBmZ2pZ8ldbjUJpPQfnavSPmy4zDB53YMYXxoG8vfaRUk6mltapKHvN+Mw0dwuc9Ez+w4XTpnOk1NEmFGpw6vTFcBKkQoj6yhzRljQKPY3cFZqUnx/FEWBC0pAsufrGR946itsZAuRSVjkRj6BnzFqs5zZeaHs07sdb75+RSqcS2yadilhJqIumD64f12qMYfQH6uICeyHMxnNZkvGwcXcc5034FTchUyAxQxc0mg2t6CZWztbSAQ9aCvQ4p2jZZLIkaATee32/MEkx9vaJP0IB/GBJ5sIoBlQdpAIRZljq6nyBkR+H18k3Pk2spePsaGaiqrggaPzGbGPHnj74ENMXoDym/lsehhNOSn8Wwzb1EfF+8AAOg3FOUq4m8G42/ed5J8WVKgP4B+Pd89tRWl2dD+DXly1dDD64vHvOyf0yzdL8FtWsGdKd6XKiOnA0GSWEjsMtj9LOaYmHEW1vANv9uBjqMcwBdRSA2xiR2+ADcP1kMYHJZcLWKjVSkPhMDlIyTQe4WAEMCyxqmufEtLbTVwhDwFtJbucSB2bS+TzrRYEjahqkTlVCnmPyYg="
    on:
      tags: true
    skip_cleanup: true
