language: node_js
node_js:
  - "10"
before_script:
  - npx version-from-git --travis --no-git-tag-version
  - npm run bootstrap
  - node scripts/syncVersion
  - npm run build
before_deploy:
  - cp -r packages/component/lib .
deploy:
  - provider: npm
    api_key:
      secure: "NeaUn7TCSG80Auzav1PfoapFYwQNdFoEK8rmnstI1q6H0aVtJErY8+50dNVxeKSifARAEr2tIu3mlJfMaTFr7VAkyCGMTcrV9KDu3D6IFsIWOx2TEGWDMFiwIqP29mtwf4qCtwgYArqMg7KuVk/cpTC+5Aha8DYLADWZyVKtO3MKYndpbhiKY0s+lv7m6tL+TXXIbBPpA96pSneKKKBEllsKLLOIujqT5Pp8enPvD4WDuHhMvqMjPhNnonZSs1x2yFDok2mLvBysxOkWns3RomasYq36L+T/lM8YJgK/WXzHKce/WupMTxx09ZnXH8tO1ON6MMqjvNXKXeIKViIt5nL7HO8uXRvuT4B5K07x5gFYx5ZtIAy0aDnMmJlkZzzFP7m9NTk2IUWK1uwTZ/sp7KsgXXgVWo9fOMK9EGZhwF4f/vCcpAurUBNYE02i6+FRjlFXw3RJ3hgdFxob0TyOu2NsaQtVfMjX4wC99vjFhwZFmgPYwsX/5NHZlQtmnB5BZuiPMKnz7hswyjs4TV+MTqEWBtBd5UILVWQRMHJE9b3dFjsX/AztgsqZ9evfl1X4dJcl7lGLmPVGjILj/P8HNW7X8VOaVeV849uyC0bLPUE9bhpxdOVjI6nlwWhWTdWezdDwyHeGug6y+yhjQX7Mex3sw1SCPKQ6kCViE8qJDtc="
    email: "compulim@hotmail.com"
    on:
      branch: master
    skip_cleanup: true
    tag: master
  - provider: npm
    api_key:
      secure: "NeaUn7TCSG80Auzav1PfoapFYwQNdFoEK8rmnstI1q6H0aVtJErY8+50dNVxeKSifARAEr2tIu3mlJfMaTFr7VAkyCGMTcrV9KDu3D6IFsIWOx2TEGWDMFiwIqP29mtwf4qCtwgYArqMg7KuVk/cpTC+5Aha8DYLADWZyVKtO3MKYndpbhiKY0s+lv7m6tL+TXXIbBPpA96pSneKKKBEllsKLLOIujqT5Pp8enPvD4WDuHhMvqMjPhNnonZSs1x2yFDok2mLvBysxOkWns3RomasYq36L+T/lM8YJgK/WXzHKce/WupMTxx09ZnXH8tO1ON6MMqjvNXKXeIKViIt5nL7HO8uXRvuT4B5K07x5gFYx5ZtIAy0aDnMmJlkZzzFP7m9NTk2IUWK1uwTZ/sp7KsgXXgVWo9fOMK9EGZhwF4f/vCcpAurUBNYE02i6+FRjlFXw3RJ3hgdFxob0TyOu2NsaQtVfMjX4wC99vjFhwZFmgPYwsX/5NHZlQtmnB5BZuiPMKnz7hswyjs4TV+MTqEWBtBd5UILVWQRMHJE9b3dFjsX/AztgsqZ9evfl1X4dJcl7lGLmPVGjILj/P8HNW7X8VOaVeV849uyC0bLPUE9bhpxdOVjI6nlwWhWTdWezdDwyHeGug6y+yhjQX7Mex3sw1SCPKQ6kCViE8qJDtc="
    email: "compulim@hotmail.com"
    on:
      tags: true
    skip_cleanup: true
  - provider: pages
    skip-cleanup: true
    github-token:
      secure: "By9mOa/fbj3aLs7CF+zKD+9n4j6D4hR2oFRoLL6dCDmCbBXOo+ddxB0U8mR9dg2abxo5cXRXU5yxfYp304Lb47YHfC/ayJAAYzvbgkn92Gq0V3jBmZ2pZ8ldbjUJpPQfnavSPmy4zDB53YMYXxoG8vfaRUk6mltapKHvN+Mw0dwuc9Ez+w4XTpnOk1NEmFGpw6vTFcBKkQoj6yhzRljQKPY3cFZqUnx/FEWBC0pAsufrGR946itsZAuRSVjkRj6BnzFqs5zZeaHs07sdb75+RSqcS2yadilhJqIumD64f12qMYfQH6uICeyHMxnNZkvGwcXcc5034FTchUyAxQxc0mg2t6CZWztbSAQ9aCvQ4p2jZZLIkaATee32/MEkx9vaJP0IB/GBJ5sIoBlQdpAIRZljq6nyBkR+H18k3Pk2spePsaGaiqrggaPzGbGPHnj74ENMXoDym/lsehhNOSn8Wwzb1EfF+8AAOg3FOUq4m8G42/ed5J8WVKgP4B+Pd89tRWl2dD+DXly1dDD64vHvOyf0yzdL8FtWsGdKd6XKiOnA0GSWEjsMtj9LOaYmHEW1vANv9uBjqMcwBdRSA2xiR2+ADcP1kMYHJZcLWKjVSkPhMDlIyTQe4WAEMCyxqmufEtLbTVwhDwFtJbucSB2bS+TzrRYEjahqkTlVCnmPyYg="
    on:
      branch: master
    local-dir: packages/playground/build
  - provider: releases
    api_key:
      secure: "By9mOa/fbj3aLs7CF+zKD+9n4j6D4hR2oFRoLL6dCDmCbBXOo+ddxB0U8mR9dg2abxo5cXRXU5yxfYp304Lb47YHfC/ayJAAYzvbgkn92Gq0V3jBmZ2pZ8ldbjUJpPQfnavSPmy4zDB53YMYXxoG8vfaRUk6mltapKHvN+Mw0dwuc9Ez+w4XTpnOk1NEmFGpw6vTFcBKkQoj6yhzRljQKPY3cFZqUnx/FEWBC0pAsufrGR946itsZAuRSVjkRj6BnzFqs5zZeaHs07sdb75+RSqcS2yadilhJqIumD64f12qMYfQH6uICeyHMxnNZkvGwcXcc5034FTchUyAxQxc0mg2t6CZWztbSAQ9aCvQ4p2jZZLIkaATee32/MEkx9vaJP0IB/GBJ5sIoBlQdpAIRZljq6nyBkR+H18k3Pk2spePsaGaiqrggaPzGbGPHnj74ENMXoDym/lsehhNOSn8Wwzb1EfF+8AAOg3FOUq4m8G42/ed5J8WVKgP4B+Pd89tRWl2dD+DXly1dDD64vHvOyf0yzdL8FtWsGdKd6XKiOnA0GSWEjsMtj9LOaYmHEW1vANv9uBjqMcwBdRSA2xiR2+ADcP1kMYHJZcLWKjVSkPhMDlIyTQe4WAEMCyxqmufEtLbTVwhDwFtJbucSB2bS+TzrRYEjahqkTlVCnmPyYg="
    on:
      tags: true
    skip_cleanup: true
